### ISSUE TITLE
generate point cloud for kf 2, size=0

### ISSUE THREAD

**Issue by andywangxb** [lrxjason/ORB-PCL-dense-points#1]
### Dataset: V1_01_easy
show global map, size=0
receive a keyframe, id = 2
generate point cloud for kf 2, size=0
show global map, size=0
receive a keyframe, id = 3
generate point cloud for kf 3, size=0
show global map, size=0
receive a keyframe, id = 4
generate point cloud for kf 4, size=0
show global map, size=0
receive a keyframe, id = 5
generate point cloud for kf 5, size=0
show global map, size=0
receive a keyframe, id = 6
generate point cloud for kf 6, size=0
show global map, size=0
receive a keyframe, id = 7
generate point cloud for kf 7, size=0
show global map, size=0
receive a keyframe, id = 8
generate point cloud for kf 8, size=0
show global map, size=0

**Comment by lrxjason** [comment]
It only works on RGB-D dataset. @andywangxb
